#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);

# Start and stop links

service_link_enhanced("freepbx", "S98", "7");
service_link_enhanced("freepbx", "K10", "6");
service_link_enhanced("freepbx", "K10", "0");
service_link_enhanced("freepbx", "K10", "1");

service_link_enhanced("httpd-fpbx", "S86", "7");
service_link_enhanced("httpd-fpbx", "K15", "6");
service_link_enhanced("httpd-fpbx", "K15", "0");
service_link_enhanced("httpd-fpbx", "K15", "1");

service_link_enhanced("dahdi", "S09", "7");
service_link_enhanced("dahdi", "K16", "6");
service_link_enhanced("dahdi", "K16", "0");
service_link_enhanced("dahdi", "K16", "1");

safe_symlink("../daemontools" , 'root/etc/rc.d/init.d/supervise/httpd-fpbx');
safe_symlink("/var/service/httpd-fpbx" , 'root/service/httpd-fpbx');
#added by stephdl
safe_symlink("../daemontools" , '/etc/rc.d/init.d/httpd-fpbx');

# Panel links

panel_link("freepbx", 'manager');
#panel_link("fop", 'manager');

# Events links

my $event = 'freepbx-update';
templates2events("/etc/amportal.conf", qw(freepbx-update bootstrap-console-save));
templates2events("/etc/asterisk/asterisk.conf", qw(freepbx-update bootstrap-console-save));
templates2events("/etc/asterisk/cdr_mysql.conf", qw(freepbx-update bootstrap-console-save));
templates2events("/etc/asterisk/manager.conf", qw(freepbx-update bootstrap-console-save));
templates2events("/etc/logrotate.d/asterisk", qw(freepbx-update bootstrap-console-save));
templates2events("/etc/httpd/conf/httpd.conf", $event);
templates2events("/etc/httpd/fpbx-conf/httpd.conf", qw(freepbx-update bootstrap-console-save conf-userpanel));
templates2events("/etc/e-smith/sql/init/30freepbx_mysql_create_database", qw(freepbx-update bootstrap-console-save));

event_link("freepbx-checkinstall", $event, "10");
event_link("freepbx-applypatch", $event, "20");
event_link("freepbx-clean-crontab", $event, "40");
event_link("freepbx-dump-astdb", "pre-backup", "30");

safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/mysql.init");
safe_symlink("sigusr1", "root/etc/e-smith/events/$event/services2adjust/httpd-e-smith");
safe_symlink("sigusr1", "root/etc/e-smith/events/$event/services2adjust/httpd-fpbx");
safe_symlink("sigusr1", "root/etc/e-smith/events/logrotate/services2adjust/httpd-fpbx");

safe_symlink("sigusr1", "root/etc/e-smith/events/conf-userpanel/services2adjust/httpd-fpbx");

# Create empty files
safe_touch("root/etc/e-smith/events/logrotate/logfiles2timestamp/var/log/httpd/fpbx_access_log");
safe_touch("root/etc/e-smith/events/logrotate/logfiles2timestamp/var/log/httpd/fpbx_error_log");
safe_touch("root/var/service/httpd-fpbx/down");

# Create empty directories
system("/bin/mkdir -p root/var/service/httpd-fpbx/supervise");
system("/bin/mkdir -p root/var/service/httpd-fpbx/log/supervise");
system("/bin/mkdir -p root/var/log/httpd-fpbx");

