#!/bin/bash

# This script will apply some patchs for freepbx on SME server

# This patch remove the redirection in fop index so it can work with a proxypass directive
if [ -e /usr/share/freepbx/patchs/fop_index_amp.proxypass.patch ]; then
        patch -N /opt/freepbx/panel/index_amp.php /usr/share/freepbx/patchs/fop_index_amp.proxypass.patch
fi

# Same for index.php
if [ -e /usr/share/freepbx/patchs/fop_index.proxypass.patch ]; then
        patch -N /opt/freepbx/panel/index.php /usr/share/freepbx/patchs/fop_index.proxypass.patch
fi


# Patch to enable FOP Layout module
if [ -e /usr/share/freepbx/patchs/retrieve_op_conf_from_mysql.layout.patch ]; then
        patch -N /var/lib/asterisk/bin/retrieve_op_conf_from_mysql.pl /usr/share/freepbx/patchs/retrieve_op_conf_from_mysql.layout.patch
fi

